#!/usr/bin/env python3
import random
import time
import os
import copy

#COSTANTI
CELL = "█"
TIME_SLEEP = 0.5
NULL = " "
griglia = []

#CREAZIONE DELLA GRIGLIA
colonne, righe = os.get_terminal_size()
lunghezza = righe -1
larghezza = colonne - 2
for i in range(lunghezza):
    RIGA = []
    for c in range(larghezza):
        prob = random.randint(0,10)
        if prob <6:
            stato = CELL
        else:
            stato = NULL
        RIGA.append(stato)
    griglia.append(RIGA)

# STAMPA GRIGLIA
def stampa_griglia(griglia_da_stampare):
    for riga in griglia_da_stampare:     
        print("".join(riga))
 #                                                              | | | |
#CALCOLO DI CONWAY                                              | |#| |
#                                                               | | | |
def calcolo_conway(griglia_n):
    global lunghezza, larghezza, temp_griglia, griglia
    count_y = 0
    count_x = 0 
    cellule_vicine = 0
    temp_griglia = copy.deepcopy(griglia_n)
    for i in range(lunghezza):
        for j in range(larghezza):
            try:
                if griglia[count_y][count_x + 1] == "█":
                    cellule_vicine += 1
            except IndexError:
                cellule_vicine +=0
            try:
                if griglia[count_y + 1][count_x + 1] == "█":
                    cellule_vicine += 1
            except IndexError:
                cellule_vicine +=0
            try:
                if griglia[count_y + 1][count_x] == "█":
                    cellule_vicine += 1
            except IndexError:
                cellule_vicine +=0
            if count_x - 1 >= 0:
                try:
                    if griglia[count_y + 1][count_x - 1] == "█":
                        cellule_vicine += 1
                except IndexError:
                    cellule_vicine +=0
            if count_x - 1 >= 0:
                try:
                    if griglia[count_y][count_x - 1] == "█":
                        cellule_vicine += 1
                except IndexError:
                    cellule_vicine +=0
            if count_x - 1 >= 0 and count_y - 1 >= 0:
                try:
                    if griglia[count_y - 1][count_x - 1] == "█":
                        cellule_vicine += 1
                except IndexError:
                    cellule_vicine +=0
            if count_y - 1 >= 0:
                try:
                    if griglia[count_y - 1][count_x] == "█":
                        cellule_vicine += 1
                except IndexError:
                    cellule_vicine +=0
            if count_y - 1 >= 0:
                try:
                    if griglia[count_y - 1][count_x + 1] == "█":
                        cellule_vicine += 1
                except IndexError:
                    cellule_vicine +=0
            if griglia[count_y][count_x] == "█":
                if cellule_vicine < 2:
                        temp_griglia[count_y][count_x] =  " "
                elif cellule_vicine == 2 or cellule_vicine == 3:
                        temp_griglia[count_y][count_x] = "█"
                elif cellule_vicine > 3:
                        temp_griglia[count_y][count_x] = " "
            elif griglia[count_y][count_x] == " ":
                if cellule_vicine == 3:
                    temp_griglia[count_y][count_x] = "█"
            cellule_vicine = 0
            count_x += 1 
        count_y+= 1
        count_x = 0
    count_y = 0
    griglia = copy.deepcopy(temp_griglia)

while True:
    calcolo_conway(griglia)
    os.system("clear") 
    stampa_griglia(griglia)
    time.sleep(TIME_SLEEP)
